apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 139675527364.dkr.ecr.us-east-1.amazonaws.com/k8s-assignment:mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
         - containerPort: 3306
           protocol: TCP
